MJ/Modules/Newsletter/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Modules\Newsletter\Http\Controllers\NewsletterController;

Route::prefix('admin')->middleware(['auth', 'doNotCacheResponse'])->group(function () {
    Route::resource('newsletters', NewsletterController::class)->except('show');
});

MJ/Modules/Newsletter/Models/Newsletter.php
<?php

namespace Modules\Newsletter\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Modules\Core\Models\Core;
use Modules\Newsletter\Database\Factories\NewsletterFactory;

class Newsletter extends Core
{
    use HasFactory;
    
    protected $table = 'newsletters';
    
    protected $casts = [
        'is_validated' => 'bool',
    ];
    
    protected $hidden = [
        'token',
    ];
    
    protected $fillable = [
        'email',
        'token',
        'is_validated',
    ];
    
    /**
     * @return NewsletterFactory
     */
    public static function Factory(): NewsletterFactory
    {
        return NewsletterFactory::new();
    }
    
}

MJ/Modules/Newsletter/Http/Controllers/Api/NewsletterController.php
<?php

namespace Modules\Newsletter\Http\Controllers\Api;

use Exception;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\ResourceCollection;
use Modules\Banner\Http\Resource\BannerResource;
use Modules\Core\Helpers\Helper;
use Modules\Core\Http\Controllers\Api\CoreController;
use Modules\Coupon\Http\Resource\CouponResource;
use Modules\Newsletter\Http\Requests\Api\Store;
use Modules\Newsletter\Http\Requests\Api\Store as Update;
use Modules\Newsletter\Http\Resources\NewsletterResource;
use Modules\Newsletter\Service\NewsletterService;

class NewsletterController extends CoreController
{
    
    private NewsletterService $newsletter_service;
    
    public function __construct(NewsletterService $newsletter_service)
    {
        $this->newsletter_service = $newsletter_service;
    }
    
    /**
     * @return ResourceCollection
     */
    public function index(): ResourceCollection
    {
        return NewsletterResource::collection($this->newsletter_service->getAll());
    }
    
    public function store(Store $request)
    {
        try {
            return $this
                ->setMessage(
                    __(
                        'apiResponse.storeSuccess',
                        [
                            'resource' => Helper::getResourceName(
                                $this->newsletter_service->newsletter_repository->model
                            ),
                        ]
                    )
                )
                ->respond(new BannerResource($this->newsletter_service->store($request->validated())));
        } catch (Exception $exception) {
            return $exception->getMessage();
        }
    }
    
    /**
     * @param $id
     *
     * @return JsonResponse|string
     */
    public function show($id)
    {
        try {
            return $this
                ->setMessage(
                    __(
                        'apiResponse.ok',
                        [
                            'resource' => Helper::getResourceName(
                                $this->newsletter_service->newsletter_repository->model
                            ),
                        ]
                    )
                )
                ->respond(new CouponResource($this->newsletter_service->show($id)));
        } catch (Exception $exception) {
            return $exception->getMessage();
        }
    }
    
    /**
     * @param  Update  $request
     * @param $id
     *
     * @return string
     */
    public function update(Update $request, $id)
    {
        try {
            return $this
                ->setMessage(
                    __(
                        'apiResponse.updateSuccess',
                        [
                            'resource' => Helper::getResourceName(
                                $this->newsletter_service->newsletter_repository->model
                            ),
                        ]
                    )
                )
                ->respond(new BannerResource($this->newsletter_service->update($id, $request->validated())));
        } catch (Exception $exception) {
            return $exception->getMessage();
        }
    }
    
    /**
     * @param $id
     *
     * @return JsonResponse|string
     */
    public function destroy($id)
    {
        try {
            return $this
                ->setMessage(
                    __(
                        'apiResponse.deleteSuccess',
                        [
                            'resource' => Helper::getResourceName(
                                $this->newsletter_service->newsletter_repository->model
                            ),
                        ]
                    )
                )
                ->respond($this->newsletter_service->destroy($id));
        } catch (Exception $exception) {
            return $exception->getMessage();
        }
    }
}

MJ/Modules/Newsletter/Http/Controllers/NewsletterController.php
<?php

namespace Modules\Newsletter\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Modules\Core\Http\Controllers\CoreController;
use Modules\Newsletter\Http\Requests\Store;
use Modules\Newsletter\Http\Requests\Store as Update;
use Modules\Newsletter\Models\Newsletter;
use Modules\Newsletter\Service\NewsletterService;

class NewsletterController extends CoreController
{
    private NewsletterService $newsletter_service;
    
    public function __construct(NewsletterService $newsletter_service)
    {
        $this->authorizeResource(Newsletter::class);
        $this->newsletter_service = $newsletter_service;
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): Factory|View|Application
    {
        return view('newsletter::index', ['newsletters' => $this->newsletter_service->getAll()]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        return view('newsletter::create', ['newsletter' => new Newsletter()]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  Store  $request
     *
     * @return RedirectResponse
     */
    public function store(Store $request): RedirectResponse
    {
        $this->newsletter_service->store($request->validated());
        
        return redirect()->route('newsletters.index');
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  Newsletter  $newsletter
     *
     * @return Application|Factory|View
     */
    public function edit(Newsletter $newsletter): View|Factory|Application
    {
        $newsletter = $this->newsletter_service->edit($newsletter->id);
        
        return view('newsletter::edit', compact('newsletter'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  Update  $request
     * @param  Newsletter  $newsletter
     *
     * @return RedirectResponse
     */
    public function update(Update $request, Newsletter $newsletter): RedirectResponse
    {
        $this->newsletter_service->update($newsletter->id, $request->validated());
        
        return redirect()->route('newsletters.index');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  Newsletter  $newsletter
     *
     * @return RedirectResponse
     */
    public function destroy(Newsletter $newsletter): RedirectResponse
    {
        $this->newsletter_service->destroy($newsletter->id);
        
        return redirect()->route('newsletters.index');
    }
    
}

MJ/Modules/Newsletter/Resources/views/create.blade.php
@extends('admin::layouts.master')

@section('title','E-SHOP || Banner Create')

@section('content')

    <div class="card">
        <h5 class="card-header">Add newsletter</h5>
        <div class="card-body">
            @include('newsletter::partials.form')
        </div>
    </div>

@endsection

@push('styles')
    <link rel="stylesheet" href="{{asset('backend/summernote/summernote.min.css')}}">
@endpush
@push('scripts')
    <script src="/vendor/laravel-filemanager/js/stand-alone-button.js"></script>
    <script src="{{asset('backend/summernote/summernote.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('#description').summernote({
                placeholder: "Write short description.....",
                tabsize: 2,
                height: 150
            });
        });
    </script>
@endpush

MJ/Modules/Newsletter/Resources/views/edit.blade.php
@extends('admin::layouts.master')

@section('title','E-SHOP || Banner Create')

@section('content')
    <div class="card">
        <h5 class="card-header">Edit newsletter</h5>
        <div class="card-body">
            @include('newsletter::partials.form')
        </div>
    </div>

@endsection

MJ/Modules/Newsletter/Resources/views/index.blade.php
@extends('admin::layouts.master')
@section('title','E-SHOP || Newsletter Page')
@section('content')
    <!-- DataTales Example -->
    <div class="card shadow mb-4">

        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary float-left">Newsletter List</h6>
            <a href="{{route('newsletters.create')}}" class="btn btn-primary btn-sm float-right" data-toggle="tooltip"
               data-placement="bottom" title="Add newsletter"><i class="fas fa-plus"></i> Add newsletter</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                @if(isset($newsletters))
                    <table class="table table-bordered" id="data-table">
                        <thead>
                        <tr>
                            <th>S.N.</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>S.N.</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @foreach($newsletters as $newsletter)
                            <tr>
                                <td>{{$newsletter->id}}</td>
                                <td>{{$newsletter->email}}</td>

                                <td>
                                    @if($newsletter->is_validated ==1)
                                        <span class="badge badge-success">Validated</span>
                                    @else
                                        <span class="badge badge-warning">Not validated</span>
                                    @endif
                                </td>
                                <td>
                                    <a href="{{route('newsletters.edit',$newsletter->id)}}"
                                       class="btn btn-primary btn-sm float-left mr-1"
                                       style="height:30px; width:30px;border-radius:50%" data-toggle="tooltip"
                                       title="edit" data-placement="bottom"><i class="fas fa-edit"></i></a>
                                    <form method="POST" action="{{route('newsletters.destroy',$newsletter->id)}}">
                                        @csrf
                                        @method('delete')
                                        <button class="btn btn-danger btn-sm dltBtn"
                                                data-id="{{$newsletter->id}}" style="height:30px; width:30px;border-radius:50%
                                        " data-toggle="tooltip" data-placement="bottom" title="Delete"><i
                                                    class="fas fa-trash-alt"></i></button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @else
                    <h6 class="text-center">No brands found!!! Please create brand</h6>
                @endif
            </div>
        </div>
    </div>
@endsection

MJ/Modules/Newsletter/Resources/views/partials/form.blade.php
@if ($newsletter->exists)
    <form class="form-horizontal" method="POST" action="{{ route('newsletters.update', $newsletter->id) }}"
          enctype="multipart/form-data">
        @method('put')
        @csrf
        @else
            <form class="form-horizontal" method="POST" action="{{ route('newsletters.store') }}"
                  enctype="multipart/form-data">
                @csrf
                @endif
                <div class="form-group">
                    <label for="inputTitle" class="col-form-label">Email <span class="text-danger">*</span></label>
                    <input id="inputTitle" type="text" name="email" placeholder="Enter email"
                           value="{{ $newsletter->email ?? null }}"
                           class="form-control">

                </div>

                <div class="form-group">
                    <label for="status" class="col-form-label">Status <span class="text-danger">*</span></label>
                    <select name="is_validated" class="form-control">
                        <option @checked($newsletter->is_validated === true) value="1">Active</option>
                        <option @checked($newsletter->is_validated === false)  value="2">Inactive</option>
                    </select>

                </div>
                <div class="form-group mb-3">
                    <button type="reset" class="btn btn-warning">Reset</button>
                    <button class="btn btn-success" type="submit">Submit</button>
                </div>
            </form>
    </form>