MJ/Modules/Category/Routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;
use Modules\Category\Http\Controllers\CategoryController;

Route::prefix('admin')->middleware(['auth', 'doNotCacheResponse'])->group(function () {
    Route::resource('/categories', CategoryController::class)->except('shows');
});

MJ/Modules/Category/Resources/views/partials/form.blade.php
@include('notification::notification')

@if($category->exists)
    <form class="form-horizontal" method="POST" action="{{ route('categories.update',$category) }}"
          enctype="multipart/form-data">
        @method('put')
        @csrf
        @else
            <form class="form-horizontal" method="POST" action="{{ route('categories.store') }}"
                  enctype="multipart/form-data">
                @csrf
                @endif
                <div class="form-group">
                    <label for="title" class="control-label">{{trans('messages.title')}}</label>

                    <input id="title" class="form-control" type="text" name="title"
                           placeholder="{{trans('messages.enter_category_title')}}"
                           value="{{ old('title', $category->title ?? null) }}"/>
                </div>
                @if ($categories == !null)
                    @if($categories>2)
                        <div class="form-group">
                            <label for="name" class="control-label">{{trans('messages.sub_category')}}</label>
                            <select name="parent_id" id="parent_id" class="form-control">
                                @if (!empty($category->getParentsNames()))
                                    <option
                                            value=""
                                            selected>{{ $category->getParentsNames()}}</option>
                                @else
                                    <option value="">Select category</option>
                                @endif
                                @if ($categories)
                                    @foreach ($categories as $categoryList)
                                        <option value="{{ $categoryList['id'] }}">{{ $categoryList['title'] }}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div>
                    @endif
                @endif
                <div class="form-group">
                    <label for="status" class="col-form-label">Status <span class="text-danger">*</span></label>
                    <select name="status" class="form-control">
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>

                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-offset-3 col-md-9">
                            <button type="submit" class="btn">@lang('messages.save')</button>
                        </div>
                    </div>
                </div>
            </form>
    </form>